#!/usr/bin/env bash
# Read-only morning packet for overnight caption catch-up.
# Writes ~/.haymish/jobs/morning-report-YYYYMMDD.md — no Photos mutations.
set -euo pipefail

REPO="${HAYMISH_REPO:-$(cd "$(dirname "$0")/.." && pwd)}"
HAY="${HOME}/.haymish"
JOB_DIR="${HAY}/jobs"
LOG_DIR="${HAY}/logs"
STAMP="$(date +%Y%m%d)"
OUT="${JOB_DIR}/morning-report-${STAMP}.md"
STATUS="${JOB_DIR}/reindex-status.json"
PIDFILE="${JOB_DIR}/reindex-catchup.pid"
INDEX_LOG="${HAY}/index.log"

mkdir -p "$JOB_DIR" "$LOG_DIR"
cd "$REPO"

{
  echo "# Haymish overnight index report — $(date '+%Y-%m-%d %H:%M %Z')"
  echo
  echo "Generated by \`scripts/haymish-morning-index-report.sh\` (read-only)."
  echo

  echo "## Catch-up process"
  if [[ -f "$PIDFILE" ]]; then
    pid="$(cat "$PIDFILE" 2>/dev/null || true)"
    if [[ -n "${pid}" ]] && kill -0 "$pid" 2>/dev/null; then
      echo "- **state:** still running (pid \`$pid\`)"
    else
      echo "- **state:** pidfile present but process not alive (pid \`${pid:-?}\`)"
    fi
  else
    echo "- **state:** no pidfile (job not running or finished)"
  fi
  if [[ -f "$STATUS" ]]; then
    echo "- **status.json:**"
    echo '```'
    cat "$STATUS"
    echo '```'
  fi
  echo

  echo "## Latest index.log progress"
  echo '```'
  if [[ -f "$INDEX_LOG" ]]; then
    grep -E 'START|DONE|ABORT|FAIL|\.\.|captioned=' "$INDEX_LOG" | tail -40
  else
    echo "(no index.log)"
  fi
  echo '```'
  echo

  echo "## Doctor (live)"
  echo '```'
  # Strip noisy macOS XPC chatter from doctor output.
  uv run haymish doctor 2>&1 | grep -vE 'Connection Invalid|hiservices|message reply' || true
  echo '```'
  echo

  echo "## Doctor --fix config (proposals only)"
  echo '```'
  uv run haymish doctor --fix config 2>&1 | grep -vE 'Connection Invalid|hiservices|message reply' || true
  echo '```'
  echo

  echo "## Find smoke (read-only)"
  echo '```'
  # Narrow smoke: does semantic find return anything without mutating Photos?
  if uv run haymish find "recipe screenshot" --top 5 2>&1 | grep -vE 'Connection Invalid|hiservices|message reply'; then
    :
  else
    echo "(find failed or returned nothing — inspect captions/embeddings above)"
  fi
  echo '```'
  echo

  echo "## What to do next (human)"
  echo "1. Skim catch-up progress vs overnight start (~3.5k captioned at kickoff 2026-09-22 evening)."
  echo "2. If failed count spiked: \`ollama ps\` — stop non-vision models hogging VRAM."
  echo "3. Paste doctor archive/delete proposals **or** set \`[global].backup\` before any delete dogfood."
  echo "4. Optional live UI: \`docs/SMOKE.md\` one small subgroup → undo (no mass apply)."
  echo "5. Product backlog from UT: fail-closed archive UI, capped review, Index catch-up perceptibility."
} > "$OUT"

echo "wrote $OUT"
